default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PWD'] %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
